language: ruby
rvm:
  - 2.3.1

services:
  - postgres

before_install:
  - if [[ `ruby -v` != 2.3.1 ]]; then
      rvm install ruby-2.3.1;
      rvm use 2.3.1 --default;
    fi
  - ruby --version

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - gem install bundler

addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-9.4-postgis-2.1

services:
  - postgresql
gemfile:
  - Gemfile

before_script:
  - psql -c 'CREATE USER cara_database_user' -U postgres
  - psql -U postgres -c "create extension postgis"

script:
  - RAILS_ENV=test bin/bundle install
  - RAILS_ENV=test bin/rails db:drop db:create db:migrate
  - bin/bundle exec rspec

after_script:
  - RAILS_ENV=test bin/rails db:drop db:create db:migrate
  - psql -c 'DROP ROLE IF EXISTS cara_database_user;' -U postgres
notifications:
  email: false