language: ruby
rvm:
  - 2.3.1

services:
  - postgres

before_install:
  - if [[ `ruby -v` != 2.3.1 ]]; then
      rvm install ruby-2.3.1;
      rvm use 2.3.1 --default;
    fi
  - ruby --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - gem install bundler

addons:
  postgresql: "9.6"

services:
  - postgresql
gemfile:
  - Gemfile

before_script:
  - createuser -d -U postgres $CARA_API_DATABASE_USERNAME

script:
  - RAILS_ENV=test bin/bundle install
  - RAILS_ENV=test bin/rails db:drop db:create db:migrate
  - bin/bundle exec rspec

after_script:
  - RAILS_ENV=test bin/rails db:drop
  - dropuser $CARA_API_DATABASE_USERNAME -U postgres
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: cara-staging-api
  on:
    branch: staging
  run:
    - "bin/rails db:migrate"
    - "bin/rails db:seed"

notifications:
  email: false