language: ruby
rvm:
  - 2.3.1

services:
  - postgres

before_install:
  - if [[ `ruby -v` != 2.3.1 ]]; then
      rvm install ruby-2.3.1;
      rvm use 2.3.1 --default;
    fi
  - ruby --version

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - gem install bundler

addons:
  postgresql: "9.4"

services:
  - postgresql
gemfile:
  - Gemfile

script:
  - bin/bundle install
  - bin/rails db:drop:all db:create db:migrate
  - bin/bundle exec rspec

notifications:
  email: false