default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['CARA-API_DATABASE_USERNAME'] %>
  password: <%= ENV['CARA-API_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cara-api_development

test:
  <<: *default
  database: cara-api_test

production:
  <<: *default
  database: <%= ENV['CARA-API_DATABASE_NAME'] %>
